### PR TITLE
tw_1

### PR DESCRIPTION
**Pull request by wyrwat**
tomasz wyrwa home task

### CODE REVIEW

**Review by azelezovs — CHANGES_REQUESTED** [review]
Did you forget to save the changes to the file or would you like to skip this part?

**Comment by wyrwat** [comment]
o i got it , there is text missing in BOOTCAM.md right ?

**Comment by wyrwat** [comment]
if that is a case it should be fixed

**Review by azelezovs — APPROVED** [review]
All good now. Thank you!

**Pull request merged**
