### PR TITLE
Hometask 1 - 'BOOTCAMP.md' file created and filled

### PR DESCRIPTION
**Pull request by bpavlovs**
Submitting 'BOOTCAMP.md', created and filled in a separate branch

### CODE REVIEW

**Review by azelezovs — CHANGES_REQUESTED** [review]
yarn installation files needs to be excluded from Pull Request, .gitignore file need to be updated accordingly if you don't want to commit such files by accident in future.
653 files changed is 652 more than it was required =)

**Comment by bpavlovs** [comment]
My bad, I've updated .gitignore file, should be fine now hopefully! :)

**Comment by bpavlovs** [comment]
5th time is the charm! 😄
Cleared cache, so that should clean up my initial commit. Let me know please, if I've missed something else.

**Review by azelezovs — APPROVED** [review]
Nice work. Thanks!

**Pull request merged**
